[package]
edition = '2018'
name = 'ton_node'
version = '0.48.22'

[workspace]
members = [ 'storage' ]
resolver = '2'

[dependencies]
zeroize_derive = '=1.2.2'
async-trait = '0.1.22'
base64 = '0.13'
bitflags = '1.2.1'
chrono = '0.4.10'
clap = '2.33.1'
colored = '1.9.3'
crossbeam-channel = '0.4.2'
dirs = '2.0.2'
env_logger = '0.7.1'
failure = '0.1'
futures = '0.3.1'
futures-timer = '3.0.1'
hex = '0.4'
lazy_static = '1.4.0'
log = '0.4'
log4rs = '1'
log4rs-rolling-file = '0.2.0'
num-bigint = '0.2.2'
openssl = '0.10.35'
rand = '0.7'
regex = '^1.3.0'
serde = '1.0.105'
serde_derive = '1.0.105'
serde_json = '1.0.64'
sha2 = '0.9'
spin = '0.7.1'
stream-cancel = '0.8.0'
string-builder = '^0.2.0'
adnl = { features = [ 'client', 'node', 'server' ], git = 'https://github.com/tonlabs/ton-labs-adnl', tag = '0.7.64' }
catchain = { path = 'catchain' }
dht = { git = 'https://github.com/tonlabs/ton-labs-dht', tag = '0.5.61' }
lockfree = { git = 'https://github.com/tonlabs/lockfree.git' }
overlay = { git = 'https://github.com/tonlabs/ton-labs-overlay', tag = '0.6.49' }
rldp = { git = 'https://github.com/tonlabs/ton-labs-rldp', tag = '0.7.60' }
rustracing = { optional = true, version = '0.4.0' }
rustracing_jaeger = { optional = true, version = '0.4.1' }
statsd = { optional = true, version = '0.14.0' }
storage = { path = 'storage' }
tokio = { features = [ 'rt-multi-thread' ], version = '1.5' }
ton_abi = { git = 'https://github.com/tonlabs/ton-labs-abi.git', tag = '2.1.7' }
ton_api = { git = 'https://github.com/tonlabs/ton-labs-tl', package = 'ton_api', tag = '0.2.117' }
ton_block = { git = 'https://github.com/tonlabs/ton-labs-block', tag = '1.7.36' }
ton_block_json = { git = 'https://github.com/tonlabs/ton-labs-block-json.git', tag = '0.6.34' }
ton_executor = { git = 'https://github.com/tonlabs/ton-labs-executor', tag = '1.15.50' }
ton_types = { git = 'https://github.com/tonlabs/ton-labs-types', tag = '1.10.12' }
ton_vm = { git = 'https://github.com/tonlabs/ton-labs-vm', tag = '1.8.29' }
validator_session = { path = 'validator-session' }

[dev-dependencies]


[features]
async_collator = [  ]
async_validator = [  ]
ci_run = [ 'storage/ci_run' ]
compression = [ 'overlay/compression', 'rldp/compression' ]
default = [ 'telemetry' ]
external_db = [ 'rdkafka' ]
metrics = [ 'statsd' ]
slashing = [  ]
telemetry = [ 'adnl/telemetry', 'dht/telemetry', 'rldp/telemetry', 'overlay/telemetry', 'storage/telemetry' ]
trace_alloc = [  ]
trace_alloc_detail = [ 'trace_alloc' ]
validator = [ 'async_collator', 'async_validator' ]

[profile]
release = { debug = true }

[target.'cfg(unix)'.dependencies.rdkafka]
optional = true
version = '0.26.0'

[target.'cfg(windows)'.dependencies.rdkafka]
features = [ 'cmake_build' ]
optional = true
version = '0.26.0'

