[package]
build = '../common/build/build.rs'
edition = '2018'
name = 'validator_session'
version = '0.0.1'

[dependencies]
backtrace = '0.3'
crc32c = '0.4'
crossbeam = '0.7'
failure = '0.1'
hex = '0.4'
lazy_static = '1.4'
log = '0.4'
metrics-core = '0.5'
metrics-runtime = '0.13'
rand = '0.8'
sha2 = '0.9'
adnl = { features = [ 'node' ], git = 'https://github.com/tonlabs/ton-labs-adnl', tag = '0.7.64' }
catchain = { path = '../catchain' }
storage = { path = '../storage' }
ton_api = { git = 'https://github.com/tonlabs/ton-labs-tl', package = 'ton_api', tag = '0.2.117' }
ton_block = { git = 'https://github.com/tonlabs/ton-labs-block', tag = '1.7.36' }
ton_types = { git = 'https://github.com/tonlabs/ton-labs-types', tag = '1.10.12' }

[dev-dependencies]
chrono = '0.4'
colored = '1.9'
env_logger = '0.7'

