[package]
build = '../common/build/build.rs'
edition = '2018'
name = 'catchain'
version = '0.1.0'

[dependencies]
base64 = '0.13'
chrono = '0.4.10'
crossbeam = '0.7.3'
ed25519-dalek = '1.0'
failure = '0.1'
futures = '0.3.4'
hex = '0.4'
lazy_static = '1.4.0'
log = '0.4'
metrics-core = '0.5.2'
metrics-runtime = '0.13.0'
rand = '0.8'
regex = '1.3.1'
sha2 = '0.9'
adnl = { features = [ 'node' ], git = 'https://github.com/tonlabs/ton-labs-adnl', tag = '0.7.64' }
overlay = { git = 'https://github.com/tonlabs/ton-labs-overlay', tag = '0.6.49' }
rldp = { git = 'https://github.com/tonlabs/ton-labs-rldp', tag = '0.7.60' }
storage = { path = '../storage' }
tokio = { features = [ 'rt-multi-thread' ], version = '1.5' }
ton_api = { git = 'https://github.com/tonlabs/ton-labs-tl', package = 'ton_api', tag = '0.2.117' }
ton_types = { git = 'https://github.com/tonlabs/ton-labs-types', tag = '1.10.12' }

[dev-dependencies]
chrono = '0.4.10'
env_logger = '0.7.1'

[target.'cfg(unix)'.dev-dependencies.rocksdb]
features = [ 'jemalloc' ]
git = 'https://github.com/rust-rocksdb/rust-rocksdb.git'

[target.'cfg(windows)'.dev-dependencies.rocksdb]
git = 'https://github.com/rust-rocksdb/rust-rocksdb.git'

